@url = http://localhost:5000
@parcelId = c42b7794-1616-4eea-b8b5-5225758f9d26

###
GET {{url}}

###
GET {{url}}/api/parcels/{{parcelId}}

###
POST {{url}}/api/parcels
Content-Type: application/json

{
  "address": "Warsaw",
  "size": "Medium"
}